# Generated by Django 5.2.1 on 2025-05-09 14:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_messsage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messsage',
            new_name='Message',
        ),
    ]
